theme: jekyll-theme-slate
title: Welcome to Triple I!
description: An open labratory for independent inter-disciplinary intellectuals. A playground for intersecting ideas that transcend traditional categories and definitions.
